### ISSUE TITLE
The image encoder in the paper is puzzling

### ISSUE THREAD

**Issue by wangtuo111** [infZhou/SAM-PD#2]
![image](https://github.com/infZhou/SAM-PD/assets/139054048/d9177958-f385-47b9-b3e1-8f7e86134010)
Is the image encoder in the diagram self-implemented, or is it using the one from the SAM model?

**Comment by infZhou** [comment]
From the SAM model. SAM-PD remains faithful to SAM and does not introduce any external models. Btw, as indicated in "Limitations and Future Work", using semantic features with better discrimination (e.g., from DINOv2) may further improve the performance of SAM-PD.
